catalogs:
  framework:
    nuxt: ^4.1.2
    sass-embedded: ^1.92.1
    typescript: ^5.9.2
    vue: ^3.5.21
    vue-router: ^4.5.1
  quality:
    '@antfu/eslint-config': ^5.3.0
    '@zinkawaii/stylelint-config': ^0.3.3
    eslint: ^9.35.0
    stylelint: ^16.24.0
  ui:
    '@nuxt/icon': ^2.0.0
    '@nuxt/image': ^1.11.0
    '@nuxtjs/color-mode': ^3.5.2
    embla-carousel-autoplay: ^8.6.0
    embla-carousel-vue: ^8.6.0
    embla-carousel-wheel-gestures: ^8.1.0
    vue-tippy: ^6.7.1
  util:
    '@nuxtjs/seo': ^3.1.0
    '@pinia/nuxt': ^0.11.2
    '@vueuse/core': ^13.9.0
    '@vueuse/nuxt': ^13.9.0
    date-fns: ^4.1.0
    fast-xml-parser: ^5.2.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi

shamefullyHoist: true
